# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 14:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171107_1609'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comments',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
